# -----------------------
# 사이트 기본 설정
# -----------------------
title: "Myeonggu's Portfolio"
description: "M.S., Student, IAI Lab, Kyung Hee University
Research Interests - AI-Driven Intelligent Manufacturing & Process
Research focus - ML / DL, Time-Series Forecasting, GNN & RL, LLM (RAG/FT)"

# 중요: 저장소 이름을 '아이디.github.io'로 했다면 baseurl은 비워둡니다.
baseurl: ""
url: "https://myoo-oong.github.io"

# -----------------------
# 사용자 정보 (서핏 내용 반영)
# -----------------------
username: "Myeonggu Kang"
user_description: "M.S., Student, IAI Lab, Kyung Hee University
Research Interests - AI-Driven Intelligent Manufacturing & Process
Research focus - ML / DL, Time-Series Forecasting, GNN & RL, LLM (RAG/FT)"
user_title: "[서핏의 '직군/직무' 예: Frontend Developer]"
email: "[이메일 주소]"

# -----------------------
# 소셜 링크 (필요한 것만 남기고 삭제하세요)
# -----------------------
twitter_username: 
github_username: "myoo-oong"
# surfit_url: "https://my.surfit.io/w/96071231" # 필요하면 주석(#)을 풀고 쓰세요

# -----------------------
# 테마 설정 (건드리지 마세요)
# -----------------------
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
gems: [jekyll-paginate, jekyll-gist]
